//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctionata.Domain.Entities.Validations.Specifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpecificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auctionata.Domain.Entities.Validations.Specifications.SpecificationMessages", typeof(SpecificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction bid rule violated.
        /// </summary>
        internal static string AuctionBidRuleViolated {
            get {
                return ResourceManager.GetString("AuctionBidRuleViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contry.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expired.
        /// </summary>
        internal static string DataExpired {
            get {
                return ResourceManager.GetString("DataExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data {0} is required.
        /// </summary>
        internal static string DataIsRequired {
            get {
                return ResourceManager.GetString("DataIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be equal or greater than {1}.
        /// </summary>
        internal static string DataShoudBeEqualOrGreaterThan {
            get {
                return ResourceManager.GetString("DataShoudBeEqualOrGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1}.
        /// </summary>
        internal static string DataShoudBeGreaterThan {
            get {
                return ResourceManager.GetString("DataShoudBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Range.
        /// </summary>
        internal static string IncrementalRange {
            get {
                return ResourceManager.GetString("IncrementalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Ranges.
        /// </summary>
        internal static string IncrementalRanges {
            get {
                return ResourceManager.GetString("IncrementalRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bid Value.
        /// </summary>
        internal static string InvalidBidValue {
            get {
                return ResourceManager.GetString("InvalidBidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum item value.
        /// </summary>
        internal static string MinimumItemValue {
            get {
                return ResourceManager.GetString("MinimumItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string NSeconds {
            get {
                return ResourceManager.GetString("NSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        internal static string RoomNumber {
            get {
                return ResourceManager.GetString("RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some {0} is invalid.
        /// </summary>
        internal static string SomeDataIsInvalid {
            get {
                return ResourceManager.GetString("SomeDataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartingBid.
        /// </summary>
        internal static string StartingBid {
            get {
                return ResourceManager.GetString("StartingBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is in Auction or Sold.
        /// </summary>
        internal static string TheItemIsInAuctionOrSold {
            get {
                return ResourceManager.GetString("TheItemIsInAuctionOrSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is in Auction or Ended.
        /// </summary>
        internal static string TheRoomIsInAuctionOrEnded {
            get {
                return ResourceManager.GetString("TheRoomIsInAuctionOrEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is not in auction.
        /// </summary>
        internal static string TheRoomIsNotInAuction {
            get {
                return ResourceManager.GetString("TheRoomIsNotInAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room is not in Auction.
        /// </summary>
        internal static string ThisRoomIsNotInAuction {
            get {
                return ResourceManager.GetString("ThisRoomIsNotInAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Streaming Endpoint.
        /// </summary>
        internal static string VideoStreamingEndpoint {
            get {
                return ResourceManager.GetString("VideoStreamingEndpoint", resourceCulture);
            }
        }
    }
}
